---
- name: Install and configure PostgreSQL
  hosts: db
  become: true
  gather_facts: false
  tags:
    - postgresql
  tasks:
    - name: Install PostgreSQL
      ansible.builtin.package:
        name: postgresql-server
        state: present

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup --initdb"
      when: not postgres_data.stat.exists

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Test PostgreSQL
      become: true
      become_user: postgres
      ansible.builtin.shell: |
        psql -c "SELECT version();"
      register: postgresql_version

    - name: Print PostgreSQL version
      ansible.builtin.debug:
        msg: "{{ postgresql_version.stdout }}"