- name: Install and configure Redis
  hosts: all
  become: true
  tags:
    - redis
  vars:
    redis_password: ansible
  tasks:
    - name: Install Redis, PostgreSQL and Apache
      hosts: all
      become: yes
      roles:
        - lab.redis
        - lab.postgresql
        - lab.apache